### ISSUE TITLE
No hay acceso de pull

### ISSUE THREAD

**Issue by AstorArico72** [Gianibruno/Trabajo-Final-Laboratorio-Programacion-I#2]
Estaba por subir mi base de datos "Biblioteca.sql" aquí.
Por favor habilita el acceso a poder subir archivos.

**Comment by PabloBarrionuevo** [comment]
No se como serán las configuraciones de acceso, si no se puede, cada uno va a tener una copia de las ramas, que acá se accede como Fork, y dentro de ese Fork hacemos nuestras modificaciones, para luego hacer Pull request al main/master del repositorio original. (Creo yo) También subí mi idea de SQL en el Fork que se crea, y quedo en Pull requests, para que Gianibruno la acepte o no.

**Comment by Gianibruno** [comment]
Astor, vamos a trabajar como dice Pablo para no pisarnos a la hora de modificar el GitHub.

**Comment by AstorArico72** [comment]
Bien. Estaré haciendo forks de éste Git y trabajando ahí.
